name: learning-travel-times
channels:
  - conda-forge
  - conda-forge/label/pythonnet_dev
  - pyg
  - pytorch-lts
dependencies:
  - python==3.8.11
  - ipykernel==6.2.0
  - ipyleaflet==0.14.0
  - ipywidgets==7.6.3
  - jupyterlab-plotly-extension>=1.0.0
  - jupyterlab==3.2.8
  - matplotlib==3.4.2
  - mlflow==1.23.1
  - numpy>=1.18.0,<=1.19.3
  - numba==0.55.2
  - openpyxl==3.0.7
  - pandas==1.3.4
  - pip==21.2.4
  - plotly==5.0.0
  - pyodbc==4.0.30
  - pytest==6.2.2
  - pytz==2020.5
  - requests==2.25.1
  - scikit-learn==1.0.1
  - scipy==1.6.1
  - seaborn==0.11.1
  - xgboost==1.5.0
  - gitpython==3.1.26
  - pytorch==1.8.2
  - pip:
    - pydot==1.4.2
    - shap==0.39.0
